[build]
    publish = "public"
    command = "echo no build command"
    node_bundler = "esbuild"

[dev]
    public = "public"
    node_bundler= "esbuild"

[[redirects]]
    from = "/api/*"
    to = "/.netlify/functions/:splat"
    status = 200